TOKEN_FILE_NAME = 'token.enc'
ENCRYPT_KEY_FILE_NAME = 'secret.key'
EMPTY_TOKEN = ''
EMPTY_CRYPTOGRAPHY_KEY = b''
SECONDS_BETWEEN_CHECKS = 2
SAVED_STREAMERS_FILE_NAME = 'streamers.json'
SAVED_STREAMERS_FILE_NAME_BACKUP = 'streamers_backup.json'
